# Generated by Django 3.1.2 on 2020-10-24 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_API', '0010_auto_20201023_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioApoyaFem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioApoyaFem', to='usuarios_API.usuariobase')),
                ('usuarioAsesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioAsesor', to='usuarios_API.usuariobase')),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_API.salachat')),
            ],
        ),
    ]
