# Generated by Django 3.1.2 on 2020-10-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_API', '0011_auto_20201024_2052'),
        ('chat_API', '0002_auto_20201024_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='autor',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios_API.usuariobase'),
        ),
    ]
