# Generated by Django 3.1.2 on 2020-10-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_API', '0011_auto_20201024_2052'),
        ('chat_API', '0003_mensaje_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salachat',
            name='usuarioApoyaFem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioApoyaFem', to='usuarios_API.usuariobase'),
        ),
        migrations.AlterField(
            model_name='salachat',
            name='usuarioAsesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioAsesor', to='usuarios_API.usuariobase'),
        ),
    ]
