# Generated by Django 3.1.2 on 2020-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_API', '0007_auto_20201023_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
