# Generated by Django 3.1.2 on 2020-10-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_API', '0008_auto_20201023_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioabogado',
            old_name='ciudadesUsuario',
            new_name='ciudadUsuario',
        ),
        migrations.RenameField(
            model_name='usuariopsicologo',
            old_name='ciudadesUsuario',
            new_name='ciudadUsuario',
        ),
    ]
