# Generated by Django 3.1.2 on 2020-10-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_API', '0009_auto_20201023_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioapoyafem',
            name='aliasUsuario',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
