# Generated by Django 3.1.2 on 2020-10-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_API', '0011_auto_20201024_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioabogado',
            name='descripcion',
            field=models.TextField(default='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioabogado',
            name='fotoPerfil',
            field=models.CharField(default='FotoDePerfil', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopsicologo',
            name='descripcion',
            field=models.TextField(default='descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopsicologo',
            name='fotoPerfil',
            field=models.CharField(default='FotoDePerfil', max_length=1000),
            preserve_default=False,
        ),
    ]
